settings:
  title: 'WebSecured Status Page'
  url: 'https://status.websecured.io' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: websecured-io # unique identifier
    name: websecured.io
    description: 'WebSecured Frontend' # default=empty
    url: 'https://websecured.io/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: api.websecured-io
    name: api.websecured.io
    description: 'WebSecured API'
    url: 'https://api.websecured.io'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true
    
  - id: 3s-no
    name: 3s.no
    description: '3Secrets'
    url: 'https://3s.no'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true
